### ISSUE TITLE
Login screen is distorted on Pixel.

### ISSUE THREAD

**Issue by faraz-ahmad** [samarthagarwal/FlutterScreens#1]
![screen shot 2018-07-23 at 12 11 00 pm](https://user-images.githubusercontent.com/3992738/43061312-65f92e50-8e72-11e8-83de-05b3a4b3a8e5.png)

Login screen is distorted on Pixel.

**Comment by samarthagarwal** [comment]
This probably because the screen size is less on a Pixel. Try reducing the padding [here](https://github.com/samarthagarwal/FlutterScreens/blob/master/lib/login_screen_1.dart#L35).

**Comment by faraz-ahmad** [comment]
It looks good now but in some devices, TextField hides behind the keyboard.

**Comment by samarthagarwal** [comment]
Wrap the root `Container` in a `SingleChildScrollView`.

**Comment by faraz-ahmad** [comment]
It's working now.
