### ISSUE TITLE
Unable to launch App

### ISSUE THREAD

**Issue by MNC-Aubin** [samarthagarwal/FlutterScreens#18]
flutter run does not launch the application while using an android emulator.

**Comment by rohan1234** [comment]
is this saying no device availabe?
i would like to work on this type of issue

**Comment by Ritik609** [comment]
Can you please tell me whether your device is connected or not. Kindly need report of flutter doctor.

**Comment by nipunattri1** [comment]
> flutter run does not launch the application while using an android emulator.

Is it working with other applications. If not report it to the flutter website or try fixing you sdk(platform tools) or adb
