### ISSUE TITLE
LoginScreen3 not responsive

### ISSUE THREAD

**Issue by UraniumR** [samarthagarwal/FlutterScreens#22]
It keeps giving me this "Bottom overflowed by x pixels" warrning

**Comment by alfredma1117** [comment]
Reduce the size of the Icons.headset_mic container.

**Comment by cv692001** [comment]
Hey @UraniumR  I am interested to work on this issue can you please help me how to proceed as I am very new to open source contribution and this can be my first contribution  👍

**Comment by aniketambore** [comment]
I fixed this issue guys !. Fixed the overflow bottom issue of all the 3 login_screens .

**Comment by imasif** [comment]
@aniketambore how?

**Comment by AvdhootJadhav** [comment]
If getting a overflow bottom error then we can wrap it with SingleChildScrollView Widget. Try it
