### ISSUE TITLE
Missing packages 'flutter_ui_challenges'?

### ISSUE THREAD

**Issue by williamsatoru** [samarthagarwal/FlutterScreens#23]
In lib/landing_pages/page1.dart - lines 3 and 4, for some reason, sadly, it requests files from other projetcts - I actually checked out flutter_ui_challenges as well and the files are there. Don't know how they got mixed in here but now the project won't run withou them.

**Comment by samarthagarwal** [comment]
I think it was a mistake while merging a pull request. I will remove the landing page. It is not supposed to use any external libraries.
